version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    container_name: frontend
    environment:
      - NODE_ENV=production
    ports:
      - "3333:3000"  # Map local port 3333 to container port 3000
    restart: always

  nginx:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    container_name: nginx
    ports:
      - "8888:80"  # Map host port 8888 to container port 80
    depends_on:
      - frontend
