version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: frontend
    environment:
      - NODE_ENV=production
    expose:
      - 3333
    restart: always

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "8888:80"  # Map host port 8888 to container port 80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./build:/usr/share/nginx/html
    depends_on:
      - frontend
