version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: frontend
    environment:
      - NODE_ENV=production
      # - PORT=3000  # Ensure the app inside the container runs on port 3000
    ports:
      - "3333:3000"  # Map local port 3333 to container port 3000
    restart: always
    # volumes:
    #   - .:/usr/src/app

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "8888:80"  # Map host port 8888 to container port 80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./build:/usr/share/nginx/html
    depends_on:
      - frontend
