name: Deploy to DigitalOcean

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: SSH into DigitalOcean Droplet
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DROPLET_IP }}
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # Navigate to the application directory
            cd /var/www/multi-app-setup/Live-Coding

            # Pull the latest code from GitHub
            git pull origin master

            # Optional: Run any database migrations
            # docker-compose exec your_service_name php artisan migrate --force

            # Rebuild and restart the Docker containers
            docker-compose down
            docker-compose build
            docker-compose up -d

            # Conditionally reload Nginx if necessary (e.g., if Nginx config has changed)
            if [ -f /path/to/your/nginx/config ]; then
              systemctl reload nginx
            fi
